setwd('~/dir/') 
#### plotting for data generated for Model_biochemical_ambiguity 
#### Plots are organised by the types of the plots, rather than in the order of the manuscript presentation. 

library(ggplot2)
library(ggpubr)


#######  load color Paletes
#####
##### tile plots 
library(viridis)
mygreyPalette<- c('#EEEEEE', '#DDDDDD', '#CCCCCC', '#BBBBBB', '#AAAAAA', '#999999', '#777777', '#555555', '#333333','#111111')
myredPalette<- c('#FFEBEE', '#FFCDD2', '#EF9A9A', '#E57373', '#EF5350', '#F44336', '#E53935', '#D32F2F', '#C62828', '#B71C1C')
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7") # first gray, second near yellow, third near blue
mypinkPalette<- c('#fef2f9', '#fcdef0', '#fac6e5', '#ffb0e1',  '#ff95d6',  '#ff80ce',  '#e76eb1',  '#cd5a91', '#b44772',  '#96304c')

#######
## 1) Sanity check: does the "Reverse Function (phenotype - to - parameter function)" agree with the  "Forward Function (parameter - to - phenotype function)" ? 
##### # Supplementary Figure 8 

# load necessary data for plotting 
# Unless stated, the files are generated by the R_code: 'Model_biochemical_ambiguity.R' 

load( 'Forwards_4_param_list.RData') # data generated from the forward function 
# see the R_code: 'dose_response_parameter_response_curves.R'
load('Even_space_4_param_singles.RData')
load('biochem_ambiguity_4_param_doub_lists.RData')

mygs<- list()
mymax<- c(7.5, 5)
for(i in 1:2) {
  for (j in 1:4) {
    mygs[[i]][[j]] = ggplot() + 
      labs(x='∆∆G', y=paste('Phenotype', names(even_space_sing)[i]), title= names(param_vals_unlis[[i]])[j]) + 
      geom_vline(xintercept = 0, lty=2) + theme_classic() + xlim(-2, 7) + ylim(-0.5, mymax[i]) + 
      geom_line(data=forwards[[i]][[j]], aes(x=param, y= pheno), size=1) +  
      geom_point(data=even_space_sing[[i]][[j]], aes(x=param, y= phen), shape=1, col='red', alpha=0.5) 
  }
}
ggarrange(mygs[[1]][[1]], mygs[[1]][[2]],mygs[[1]][[3]],mygs[[1]][[4]],
          mygs[[2]][[1]], mygs[[2]][[2]],mygs[[2]][[3]],mygs[[2]][[4]], 
          nrow=2, ncol=4)


###2) Double mutants 
mywts_out<- list(pr= 0.03, prm=2.73)
##### 2.1 tile plots of double mutants' phenotypes, when there is no ambiguity 
# Fig. 1, 2
ggplot(data=doubs[[1]]) + geom_tile(aes(x= pheno1, y= pheno2, fill= pheno))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B', title='PR') + scale_fill_viridis( name= 'Mutation AB') + 
  geom_vline(xintercept = mywts_out[[1]], lty=2) + geom_hline(yintercept =   mywts_out[[1]], lty=2)+ facet_wrap(.~whichparam)  

ggplot(data=doubs[[2]][doubs[[2]]$whichparam=='t,t', ]) + geom_tile(aes(x= pheno1, y= pheno2, fill= pheno))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B', title='PR') + scale_fill_viridis( name= 'Mutation AB') + 
  geom_vline(xintercept = mywts_out[[2]], lty=2) + geom_hline(yintercept =   mywts_out[[2]], lty=2)

##### 2.2 tile plots when there is ambiguity 
# Fig. 1, 2
total<- rbind(biochem_ambi[[3]][[1]], biochem_ambi[[3]][[2]])
ones<- unique(total[total$allowed_biochem==1, 'which_biochem'])
ambiPlot<- list()

ambiPlot[[1]] <- ggplot(data=total[total$allowed_biochem==1 & total$whichpheno=='PRM', ]) + geom_tile(aes(x= p1, y= p2, fill=as.factor(ambiNum)))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_manual(values= cbPalette) + 
  labs(fill='') + facet_grid(which_biochem~.) + 
  geom_vline(xintercept = mywts_out[[2]], lty=2) + geom_hline(yintercept =   mywts_out[[2]], lty=2)

ambiPlot[[2]] <- ggplot(data=total[total$allowed_biochem==1 & total$whichpheno=='PRM', ]) + geom_tile(aes(x= p1, y= p2, fill= ambiDiff))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_gradientn(colours = c(mygreyPalette[2], myredPalette))  + 
  labs(fill='') + facet_grid(which_biochem~.) + 
  geom_vline(xintercept = mywts_out[[2]], lty=2) + geom_hline(yintercept =   mywts_out[[2]], lty=2)

ggarrange(ambiPlot[[1]] ,ambiPlot[[2]] , nrow=1, ncol=2) 

## Fig.3 & Fig. S4 When there is biochemical uncertainty between two biochemical parameters 
#####


ambiPlot<- list()
ambiPlot[[1]] <- ggplot(data=biochem_ambi[[3]][[1]]) + geom_tile(aes(x= p1, y= p2, fill=as.factor(ambiNum)))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_manual(values= c(cbPalette[1:4], mypinkPalette)) + 
  labs(fill='') + facet_grid(. ~which_biochem) + 
  geom_vline(xintercept = mywts_out[[1]], lty=2) + geom_hline(yintercept = mywts_out[[1]], lty=2)

ambiPlot[[2]] <- ggplot(data=biochem_ambi[[3]][[2]]) + geom_tile(aes(x= p1, y= p2, fill=as.factor(ambiNum)))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_manual(values= c(cbPalette[1:4], mypinkPalette)) + 
  labs(fill='') + facet_grid(. ~which_biochem) + 
  geom_vline(xintercept = mywts_out[[2]], lty=2) + geom_hline(yintercept = mywts_out[[2]], lty=2)
ggarrange(ambiPlot[[1]], ambiPlot[[2]], nrow=2, ncol=1)
###

ambiPlot[[1]] <- ggplot(data=biochem_ambi[[3]][[1]]) + geom_tile(aes(x= p1, y= p2, fill= ambiDiff))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_gradientn(colours = c(mygreyPalette[2], myredPalette))  + 
  labs(fill='') + facet_grid(.~which_biochem) + 
  geom_vline(xintercept = mywts_out[[1]], lty=2) + geom_hline(yintercept =   mywts_out[[1]], lty=2)


ambiPlot[[2]] <- ggplot(data=biochem_ambi[[3]][[2]]) + geom_tile(aes(x= p1, y= p2, fill= ambiDiff))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_gradientn(colours = c(mygreyPalette[2], myredPalette[c(1:8)]))  + 
  labs(fill='') + facet_grid(.~which_biochem) + 
  geom_vline(xintercept = mywts_out[[2]], lty=2) + geom_hline(yintercept =   mywts_out[[2]], lty=2)

ambiPlot[[2]]
ggarrange(ambiPlot[[1]], ambiPlot[[2]], nrow=2, ncol=1)


##### 2.3 examples of how two mutations combine, with ambiguity 
### Fig. 1, 2 

myphenos<- c(0.1, 1.5, 2.7, 4)

tmp<- data.frame(doubs[[2]][doubs[[2]]$paramtyp=='same' & doubs[[2]]$pheno1%in% myphenos, ])
for (i in 1:length(rownames(tmp))) { 
  tmp[i, 'ambiNum'] = mycombo_ci_inrows[[2]][str_sub(mycombo_ci_inrows[[2]]$which_biochem,1,1)==tmp[i,'type1'] & 
                                               mycombo_ci_inrows[[2]]$allowed_biochem==1 & 
                                               mycombo_ci_inrows[[2]]$p1== tmp[i,'pheno1'] & 
                                               mycombo_ci_inrows[[2]]$p2== tmp[i,'pheno2'], 'ambiNum']
  
}
# Fig. 1,2 
ggplot(data= tmp) + 
  geom_point(aes(x= pheno2, y=pheno, col= as.factor(ambiNum)), shape=1) + 
  facet_grid(type1~ as.factor(pheno1)) + theme_classic() + scale_colour_manual(values=cbPalette)

# Fig. S2, in a different scale  
ggplot(data= tmp) + 
  geom_point(aes(x= pheno2, y=pheno, col= as.factor(ambiNum)), shape=1) + 
  facet_grid(type1~ as.factor(pheno1)) + theme_classic() + scale_colour_manual(values=cbPalette)+ 
  scale_y_log10()

#### For Fig. S3 when two mutations each affecting a different biochemical parameterse are combined 
# For PRM
load('biochem_ambiguity_doubs_twodiff_params_lists.RData') 
ambiPlot<- list()

ambiPlot[[1]] <- ggplot(data=mycombs_inrow) + geom_tile(aes(x= p1, y= p2, fill=as.factor(ambiNum)))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_manual(values= cbPalette) + 
  labs(fill='') + facet_grid(type1~type2) + 
  geom_vline(xintercept = 2.73, lty=2) + geom_hline(yintercept =   2.73, lty=2) + 
  geom_abline(intercept = 0, slope = 1, col='gray')


ambiPlot[[2]] <- ggplot(data=mycombs_inrow) + geom_tile(aes(x= p1, y= p2, fill= ambiDiff))+ 
  theme_classic() + labs(x= 'Mutation A', y='Mutation B') + scale_fill_gradientn(colours = c(mygreyPalette[2], myredPalette))  + 
  labs(fill='') + facet_grid(type1~type2) + 
  geom_vline(xintercept = 2.73, lty=2) + geom_hline(yintercept =   2.73, lty=2) +
  geom_abline(intercept = 0, slope = 1, col='gray')


ggarrange(ambiPlot[[1]] ,ambiPlot[[2]] , nrow=1, ncol=2)  

###  For Fig. 3 & Fig. S4, with biochemical ambiguity of 2
to_plot<- list(pr= c(1,3,5), prm= c(0.1, 2, 4))
dev.off()

potential<- list(c('f', 'b'), c('f', 'd'), c('f','t'), c('b', 'd'), c('d','t'), c('b','t'))
mylabs= c('F or B' , 'F or D', 'F or T', 'D or B' , 'D or T', 'B or T')
tmp<- list(pr=list(), prm=list())
mycols<- list(pr=list(cbPalette[c(3,4)], cbPalette[c(3,4)], cbPalette[1:4],cbPalette[c(3,4)], cbPalette[c(1:4)], cbPalette[1:4] ), 
              prm= list(c(cbPalette[c(3,4)], mypinkPalette[c(2:10)]), c(cbPalette[c(3,4)], mypinkPalette[c(2:10)]), c(cbPalette[1:4], mypinkPalette[c(2:10)]), 
                        c(cbPalette[c(3,4)], mypinkPalette[c(2:10)]),  c(cbPalette[1:4], mypinkPalette[c(2:10)]), c(cbPalette[1:4], mypinkPalette[c(2:10)])))
for (i in 1:2) {
  for (j in 1:6){
    tmp[[i]][[j]]= doubs[[i]][doubs[[i]]$pheno1%in% to_plot[[i]] &  (doubs[[i]]$type1%in% potential[[j]]) & (doubs[[i]]$type2%in% potential[[j]]), ]
    for (k in 1:3) {
      x<- tmp[[i]][[j]][tmp[[i]][[j]]$pheno1== to_plot[[i]][k] , ]
      p2<- as.numeric(unique(x$pheno2))
      for (l in 1:length(p2)) {
        x1<- length(unique(x[x$pheno2==p2[l], 'pheno']))
        tmp[[i]][[j]][tmp[[i]][[j]]$pheno1== to_plot[[i]][k] & tmp[[i]][[j]]$pheno2==p2[l], 'ambiNum'] = x1
      }
    }
  } 
}

mygs<- list()
for (i in 1:6) {
  mygs[[i]]= ggplot(data= tmp[[1]][[i]])  + geom_point(aes(x=pheno2, y= pheno,color= as.factor(ambiNum)), shape=1) + 
    facet_grid(.~as.factor(pheno1)) + theme_classic() + scale_colour_manual(values=mycols[[1]][[i]]) + 
    labs(x= 'Mutation B', y='Mutation AB', title= mylabs[i])
}

mygs[[1]]
mygs[[2]]
mygs[[3]]
ggarrange(mygs[[1]], mygs[[2]], mygs[[3]], 
          mygs[[4]], mygs[[5]], mygs[[6]], nrow=3, ncol=2)
mygs<- list()
for (i in 1:6) {
  mygs[[i]]= ggplot(data= tmp[[2]][[i]])  + geom_point(aes(x=pheno2, y= pheno,color= as.factor(ambiNum)), shape=1) + 
    facet_grid(.~as.factor(pheno1)) + theme_classic() + scale_colour_manual(values=mycols[[2]][[i]]) + 
    labs(x= 'Mutation B', y='Mutation AB', title= mylabs[i])
}

ggarrange(mygs[[1]], mygs[[2]], mygs[[3]], 
          mygs[[4]], mygs[[5]], mygs[[6]], nrow=3, ncol=2)



##### 2.4 Ambiugity jitter plots (Fig.3 and Supplementary Fig. 4 ) 
## Fig. 4 
mygs<- list() # ambiguity Number
mygs2<- list() # ambiguity range
for (i in 1:2) {
  mygs[[i]] = ggplot(data=biochem_ambi[[4]][[i]], aes(x=as.factor(bioche_no), y= Max_ambiNum)) + 
    labs(x="# allowed biochemical changes", y= "Max_ambiguities", title= names(mycombo_ci_inrows)[i]) +theme_classic() + 
    stat_summary(fun.y="mean",geom="crossbar", 
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.5)+ 
    geom_jitter(alpha=0.4 , size=3, position =position_jitterdodge())
}

### values 
for (i in 1:2) {
  mygs2[[i]] = ggplot(data=biochem_ambi[[4]][[i]], aes(x=as.factor(bioche_no), y= Max_ambiDiff)) + 
    labs(x="# allowed biochemical changes", y= "Max_ambiguiDiff", title= names(mycombo_ci_inrows)[i]) +theme_classic() + 
    stat_summary(fun.y="mean",geom="crossbar", 
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.5)+ 
    geom_jitter(alpha=0.4 , size=3,  width = 0.1) 
}
ggarrange(mygs[[1]], mygs2[[1]],mygs[[2]], mygs2[[2]], nrow=1, ncol=4)


# Fig. S5
for (i in 1:2) {
  mygs[[i]] = ggplot(data=biochem_ambi[[4]][[i]], aes(x=as.factor(bioche_no), y= Med_ambiNum)) + 
    labs(x="# allowed biochemical changes", y= "Med_ambiNum", title= names(mycombo_ci_inrows)[i]) +theme_classic() +  
    stat_summary(fun.y="mean",geom="crossbar", 
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.5)+ 
    geom_jitter(alpha=0.4 , size=3, position =position_jitterdodge()) 
}

### values 
for (i in 1:2) {
  mygs[[i]] = ggplot(data=biochem_ambi[[4]][[i]], aes(x=as.factor(bioche_no), y= Max_ambiDiff)) + 
    labs(x="# allowed biochemical changes", y= "Max_ambiguiDiff", title= names(mycombo_ci_inrows)[i]) +theme_classic() + 
    stat_summary(fun.y="mean",geom="crossbar", 
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.5)+ 
    geom_jitter(alpha=0.4, aes(col=as.factor(invol_f), shape=as.factor(bioche_no)) , size=3,  width = 0.1)
}

for (i in 1:2) {
  mygs2[[i]] = ggplot(data=biochem_ambi[[4]][[i]], aes(x=as.factor(bioche_no), y= Med_ambiDiff)) + 
    labs(x="# allowed biochemical changes", y= "Med_ambiguiDiff", title= names(mycombo_ci_inrows)[i]) +theme_classic() +  
    stat_summary(fun.y="mean",geom="crossbar", 
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.5)+ 
    geom_jitter(alpha=0.4 , size=3, width = 0.1) 
}

ggarrange(mygs[[1]], mygs2[[1]],mygs[[2]], mygs2[[2]], nrow=1, ncol=4)

#### 3) With pleiotropic mutants 
load('pleiotropic_doub_with_one_not_list.RData')  
#### reshape for plotting
dobs<- list()
dobs[[1]] = rbind(doubs_with_pleio[[1]][[1]][, c(1:7, 9)], 
                  doubs_with_pleio[[1]][[2]][, c(1:7, 9)])
dobs[[2]] = rbind(doubs_with_pleio[[2]][[1]][, c(1:7, 9)], 
                  doubs_with_pleio[[2]][[2]][, c(1:7, 9)])
for (i in 1:2) {
  for (j in 3:4) {
    dobs[[i]]= rbind(dobs[[i]], doubs_with_pleio[[i]][[j]])
  }
}
for (i in 1:2){
  dobs[[i]]$P2_which= factor(dobs[[i]]$P2_which, levels=c('f','d', 'b', 't'))
}

# If not loaded, load the nonpleiotropic double data 
load('biochem_ambiguity_4_param_doub_lists.RData') # if already loaded, no need

#  to compare the non-pleiotropic mutants with the pleiotropic mutants 
subs<- list(doubs[[1]][doubs[[1]]$pheno1==1 & doubs[[1]]$type1%in% c('f', 'b'), ], 
            doubs[[2]][doubs[[2]]$pheno1==1 & doubs[[2]]$type1%in% c('f', 'b'), ])# 'doubs' is the nonpleiotropic data frame 
for (i in 1:2){ 
  names(subs[[i]])[c(1:4)] = c('P1', 'P2', 'P1_which', 'P2_which')
}
# PR 
ggplot(data= dobs[[1]][dobs[[1]]$P1==1, ]) + 
  geom_point(aes(x= P2, y=doubP, col=P2_which), alpha=0.2, shape=3, size=1) + 
  facet_grid(.~ P2_which) + theme_classic() + 
  scale_color_manual(values = c('red', 'blue', 'magenta', 'orange')) + 
  labs(x='Mutation B', y='Mutation AB', title= 'A: Folding+Binding') + 
  geom_point(data= subs[[1]][subs[[1]]$P1_which=='f', ], aes(x= P2, y=pheno), shape=1, alpha=0.5, size=0.5) + 
  geom_point(data= subs[[1]][subs[[1]]$P1_which=='b', ], aes(x= P2, y=pheno), shape=1, col='gray', alpha=0.5, size=0.5)

# PRM 
ggplot(data= dobs[[2]][dobs[[2]]$P1==1, ]) + 
  geom_point(aes(x= P2, y=doubP, col=P2_which), alpha=0.2, shape=3, size=1) + 
  facet_grid(.~ P2_which) + theme_classic() + 
  scale_color_manual(values = c('red', 'blue', 'magenta', 'orange')) + 
  labs(x='Mutation B', y='Mutation AB', title= 'A: Folding+Binding') + 
  geom_point(data= subs[[2]][subs[[2]]$P1_which=='f', ], aes(x= P2, y=pheno), shape=1, alpha=0.5, size=0.5) + 
  geom_point(data= subs[[2]][subs[[2]]$P1_which=='b', ], aes(x= P2, y=pheno), shape=1, col='gray', alpha=0.5, size=0.5)

rm(subs)
####### violin plot for two given single mutants' phenotypes 
load('pleiotropic_doub_both.RData') 
for (i in 1:2){
  dobs[[i]]$P1_which= as.character(dobs[[i]]$P1_which)
}
xx<- list()
for (i in 1: 2) {
  xx[[i]]= doubs_with_pleio_pleio[[i]][doubs_with_pleio_pleio[[i]]$P1 ==1 & doubs_with_pleio_pleio[[i]]$P2 ==1, ]
  xx[[i]]$P1_which= 'p'# pleiotropic
} 

toplot<- list() 
for (i in 1:2) {
  toplot[[i]]= rbind(dobs[[i]][dobs[[i]]$P1==1, c('P1_which', 'pheno')], 
                     xx[[i]][, c('P1_which', 'pheno')]) 
  
  toplot[[i]]$P1_which = factor(toplot[[i]]$P1_which, levels=c('f','d','b','t','p'))
}
# PR 
ggplot(data= toplot[[1]], aes(x= as.factor(P1_which), y= pheno, col=P1_which)) + 
  geom_violin(scale="width", fill="white", draw_quantiles = 0.5 ) + 
  theme_classic() + labs(x= 'Mutation B type', y='Mutation AB') + 
  scale_color_manual(values= c('red', 'blue', 'magenta', 'orange', 'black'))
# PRM 
ggplot(data= toplot[[2]], aes(x= as.factor(P1_which), y= pheno, col=P1_which)) + 
  geom_violin(scale="width", fill="white", draw_quantiles = 0.5 ) + 
  theme_classic() + labs(x= 'Mutation B type', y='Mutation AB') + 
  scale_color_manual(values= c('red', 'blue', 'magenta', 'orange', 'black'))
#####   
###### pleiotropy, how do they combine?  Fig.4 and Fig. S5  
load('Pleio_sings_forward_all_for_later.RData')
ss<- myPleioSing[[1]]  
for(i in 2:6){
  ss<- rbind(ss, myPleioSing[[i]])
}
ss$whichTwo= factor(ss$whichTwo, levels=c('FD', 'FB', 'FT', 'DB', 'DT', 'BT'))
# PR
ggplot(data=ss,aes(x= ddx, y= ddy, fill= PR)) + geom_tile()+ 
  theme_classic() + labs(x= '', y='') + scale_fill_viridis( name= 'Mutation Phenotype') +   
  geom_point(aes(x=0, y=0), shape= 3, col='white') + 
  geom_contour(aes(x = ddx, y = ddy, z =PR,colour = ..level..),binwidth=0.5 , col='gray') +
  facet_wrap( whichTwo~.)

# PRM
ggplot(data=ss,aes(x= ddx, y= ddy, fill= PR)) + geom_tile()+ 
  theme_classic() + labs(x= '', y='') + scale_fill_viridis( name= 'Mutation Phenotype') +   
  geom_point(aes(x=0, y=0), shape= 3, col='white') + 
  geom_contour(aes(x = ddx, y = ddy, z =PR,colour = ..level..),binwidth=0.5 , col='gray') +
  facet_wrap( whichTwo~.)

######
##### How do two mutations each with a phenotype PR~  0.5  or PRM ~ 4 combine in the parameter space
biochem_combos<- list()
mydoub2<- list()
for(i in 1:6){
  biochem_combos2[[i]]<- myPleioSing[[i]][myPleioSing[[i]]$PR>=0.45  & myPleioSing[[i]]$PR<0.55, ] 
  mydoub2[[i]]<- expand.grid(ddx1= biochem_combos2[[i]]$ddx, ddx2=  biochem_combos2[[i]]$ddx)
  tmp<- expand.grid(ddy1= biochem_combos2[[i]]$ddy, ddy2=  biochem_combos2[[i]]$ddy)
  mydoub2[[i]]<- cbind(mydoub2[[i]],tmp)

  mydoub2[[i]]$ddx= mydoub2[[i]]$ddx1 + mydoub2[[i]]$ddx2
  mydoub2[[i]]$ddy= mydoub2[[i]]$ddy1 + mydoub2[[i]]$ddy2

  mydoub2[[i]]$whichTwo = names(whichtwos)[i]
}
dd<- mydoub2[[1]]
for(i in 2:6){
  dd<- rbind(dd, mydoub2[[i]])
}
dd$whichTwo= factor(dd$whichTwo, levels=c('FD', 'FB', 'FT', 'DB', 'DT', 'BT'))


######## mycombos3 bs PRM
biochem_combos3<- list()
mydoub3<- list()
for(i in 1:6){
  biochem_combos3[[i]]<- myPleioSing[[i]][myPleioSing[[i]]$PRM>=3.9  & myPleioSing[[i]]$PRM<=4.1  , ] 

  mydoub3[[i]]<- expand.grid(ddx1= biochem_combos3[[i]]$ddx, ddx2=  biochem_combos3[[i]]$ddx)
  tmp<- expand.grid(ddy1= biochem_combos3[[i]]$ddy, ddy2=  biochem_combos3[[i]]$ddy)
  mydoub3[[i]]<- cbind(mydoub3[[i]],tmp)

  mydoub3[[i]]$ddx= mydoub3[[i]]$ddx1 + mydoub3[[i]]$ddx2
  mydoub3[[i]]$ddy= mydoub3[[i]]$ddy1 + mydoub3[[i]]$ddy2

  mydoub3[[i]]$whichTwo = names(whichtwos)[i]
}

# For PR
ggplot(data=ss,aes(x= ddx, y= ddy)) + 
  theme_classic() + labs(x= '', y='') + 
  geom_point(aes(x=0, y=0), shape= 3) + 
  #geom_contour(aes(x = ddx, y = ddy, z =PR,colour = ..level..),binwidth=0.5 ) +
  #scale_color_manual(values = mygreyPalette[c(3:10)]) +
  #geom_line(data= ss[ss$PR_round==0.1, ], aes(x= ddx, y= ddy), lty=2, col='gray')  + 
  facet_wrap( whichTwo~.)  +
  geom_point(data= dd, aes(x= ddx, y= ddy), shape=4, alpha=0.5)  + 
  #scale_color_viridis ()  + 
  xlim(-1, 5) + ylim(-1,5)


###############
dd<- mydoub3[[1]]
for(i in 2:6){
  dd<- rbind(dd, mydoub3[[i]])
}
dd$whichTwo= factor(dd$whichTwo, levels=c('FD', 'FB', 'FT', 'DB', 'DT', 'BT'))

ggplot(data=ss,aes(x= ddx, y= ddy)) + 
  theme_classic() + labs(x= '', y='') + 
  geom_point(aes(x=0, y=0), shape= 3) + 
  #geom_contour(aes(x = ddx, y = ddy, z =PR,colour = ..level..),binwidth=0.5 ) +
  #scale_color_manual(values = mygreyPalette[c(3:10)]) +
  #geom_line(data= ss[ss$PR_round==0.1, ], aes(x= ddx, y= ddy), lty=2, col='gray')  + 
  facet_wrap( whichTwo~.)  +
  geom_point(data= dd, aes(x= ddx, y= ddy), shape=4)  + 
  #scale_color_viridis ()  + 
  xlim(-1, 5) + ylim(-1,5)
geom_point(aes(x= 1, y=0), col='red',size= 2) + 
  geom_point(aes(x=1, y= 2.2), col='orange', shape= 4, size= 3) + 
  geom_point(aes(x=0, y= 4.4), col='magenta', shape= 4, size= 3) + 
  geom_point(aes(x=2, y= 0), col='red', shape= 4, size= 3)  #
###### prm 

# For PRM
ggplot(data=ss,aes(x= ddx, y= ddy)) + 
  theme_classic() + labs(x= '', y='') + 
  geom_point(aes(x=0, y=0), shape= 3) + 
  #geom_contour(aes(x = ddx, y = ddy, z =PR,colour = ..level..),binwidth=0.5 ) +
  #scale_color_manual(values = mygreyPalette[c(3:10)]) +
  #geom_line(data= ss[ss$PR_round==0.1, ], aes(x= ddx, y= ddy), lty=2, col='gray')  + 
  facet_wrap( whichTwo~.)  +
  geom_point(data= dd, aes(x= ddx, y= ddy), shape=4, alpha=0.5)  + 
  #scale_color_viridis ()  + 
  xlim(-1, 5) + ylim(-1,5)

#### 
#### Summary Plot. Fig.5 3D-biochemical landscape 
load('Reverse_anyof3_param_0.1_3_as_prPheno.RData')
load('Reverse_anyof3_param_0.1_3_as_prPheno_doub_comb_pr_prm75219260.RData')

##### try the package geometry
#### make alpha shape 
library(geometry)
library(alphashape3d)

xx<- ABs[sample(nrow(ABs), 1000000), ] # too big to calculate
tmp3<-  as.matrix(xx[, c(9:11)])
rm(xx)

tmp<- as.matrix(pleio3[[1]][, c(1:3)])
ashape3d.obj <- ashape3d(tmp, alpha = 1, pert= TRUE) # alpha increases, with density of the surface
plot(ashape3d.obj, col = 'gray')
bg3d("white")
plot3d(ashape3d.obj, col = 'red', xlim= c(-3, 10), ylim= c(-3, 12), zlim= c(-5, 7))
writeWebGL(filename = file.path("As.html"))

tmp2<- as.matrix(pleio3[[2]][, c(1:3)])
ashape3d.obj2 <- ashape3d(tmp2, alpha =5.6, pert= TRUE) # more sparse, to smooth further
plot3d(ashape3d.obj2, col = 'cyan', xlim= c(-3, 10), ylim= c(-3, 12), zlim= c(-5, 7))
writeWebGL(filename = file.path("Bs.html"))

ashape3d.obj3 <- ashape3d(tmp3, alpha =1)
plot3d(ashape3d.obj3, col = 'orange', xlim= c(-3, 10), ylim= c(-3, 12), zlim= c(-5, 7))
writeWebGL(filename = file.path("ABs.html"))

shape3d.obj2b<- ashape3d(ashape3d.obj2, alpha =8)
plot3d(shape3d.obj2b, col = 'cyan', xlim= c(-3, 10), ylim= c(-3, 12), zlim= c(-5, 7))



